logstash:
  image: logstash:1.5
  command: logstash -f /config/logstash.conf -vv
  volumes:
    - "$PWD/config:/config:ro"
  ports:
    - "3333:3333"
sinatra:
  build: sinatra
  command: rackup -o 0.0.0.0 -p 9292
nginx:
  image: nginx:1.9
  command: nginx
  ports:
    - "9292:80"
  volumes:
    - "$PWD/config/nginx.conf:/etc/nginx/nginx.conf:ro"
  links:
    - sinatra:sinatra
logstashforwarder:
  build: logstash-forwarder
  command: logstash-forwarder -config /config/logstash-forwarder.json
  volumes:
    - "$PWD/config:/config:ro"
  links:
    - logstash:logstash.example.com
